[package]
name = "attributes"
version = "0.1.0"
authors = ["Artem Korotkov <ars.korotkov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
maplit = "1.0"